[workspace]
members = [
    "crates/dxlog",
    "crates/dxlog-cli",
    "crates/dxlog-tools"
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2021"

[workspace.dependencies]
anyhow = "1.0.95"
axum = "0.7.0"
chrono = "0.4.39"
clap = { version = "4.5.26", features = ["derive"] }
git2 = "0.20.0"
indexmap = { version = "2.0", features = ["serde"] }
minijinja = "2.6.0"
petgraph = "0.6"
pulldown-cmark = "0.12.0"
regex = "1.0"
serde = { version = "1.0.217", features = ["derive"] }
serde_json = "1.0.132"
serde_yaml = "0.9.34"
thiserror = "2.0.11"
tokio = { version = "1.0", features = ["full"] }
toml = "0.8.19"
tower-http = { version = "0.6.0", features = ["fs"] }
uuid = { version = "1.12.0", features = ["v4", "serde"] }
walkdir = "2.0"
